[book]
authors = ["SilentVoid13"]
language = "zh-CN"
multilingual = false
src = "src"
title = "Templater"

[preprocessor.tera]
command = "mdbook-tera --toml ./documentation.toml"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]