name: Plugin release

on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: write
            attestations: write
            artifact-metadata: write
        steps:
            - uses: actions/checkout@v5

            - name: Use Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: "20.x"

            - name: Use pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10

            - name: Install dependencies
              run: pnpm install

            - name: Lint code
              run: pnpm lint

            - name: Build plugin
              run: pnpm build

            - name: Generate artifact attestation
              uses: actions/attest@v4
              with:
                  subject-path: |
                      main.js
                      styles.css

            - name: Create zip archive
              run: |
                  zip -j templater-obsidian.zip main.js manifest.json styles.css

            - name: Create release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  tag="${GITHUB_REF#refs/tags/}"

                  gh release create "$tag" \
                    --title="$tag" \
                    --draft \
                    main.js manifest.json styles.css templater-obsidian.zip
